"""add quantity and destination/source columns to movement

Revision ID: 4e56719c5d78
Revises: ff27ad2c156b
Create Date: 2025-07-27 21:07:27.348860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e56719c5d78"
down_revision: Union[str, Sequence[str], None] = "ff27ad2c156b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movements", sa.Column("source", sa.String(), nullable=True))
    op.add_column("movements", sa.Column("destination", sa.String(), nullable=True))
    op.add_column("movements", sa.Column("quantity", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movements", "quantity")
    op.drop_column("movements", "destination")
    op.drop_column("movements", "source")
    # ### end Alembic commands ###
