"""init migration

Revision ID: ff27ad2c156b
Revises:
Create Date: 2025-07-27 16:47:04.715569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff27ad2c156b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "warehouses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("movement_id", sa.UUID(), nullable=False),
        sa.Column("event", sa.String(length=50), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("warehouse_id", sa.UUID(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_movements_event"), "movements", ["event"], unique=False)
    op.create_index(
        op.f("ix_movements_movement_id"), "movements", ["movement_id"], unique=False
    )
    op.create_table(
        "warehouse_product_association",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("warehouse_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("warehouse_product_association")
    op.drop_index(op.f("ix_movements_movement_id"), table_name="movements")
    op.drop_index(op.f("ix_movements_event"), table_name="movements")
    op.drop_table("movements")
    op.drop_table("warehouses")
    op.drop_table("products")
    # ### end Alembic commands ###
